name: Сборка APK

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: kivy/buildozer:latest
    steps:
      - name: Клонирование проекта
        uses: actions/checkout@v4

      - name: Кэш для Android SDK/NDK
        uses: actions/cache@v4
        with:
          path: ~/.buildozer
          key: buildozer-cache

      - name: Сборка APK
        run: buildozer -v android debug

      - name: Загрузка APK
        uses: actions/upload-artifact@v4
        with:
          name: fuelbot-apk
          path: bin/*.apk
          if-no-files-found: error
